# Generated by Django 3.0 on 2021-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=50)),
                ('playerHeight', models.CharField(max_length=4)),
                ('playerTeam', models.CharField(max_length=50)),
                ('playerGoals', models.CharField(max_length=50)),
                ('playerTotalMatches', models.CharField(max_length=50)),
                ('playerImg', models.CharField(max_length=50)),
            ],
        ),
    ]
