# Generated by Django 3.0 on 2021-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='playerImg',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
